services:
  postgres:
    image: postgres:18-alpine
    container_name: sub_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_OUTSIDE}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub_tracker_app
    restart: always
    ports:
      - "${APP_PORT_OUTSIDE}:${APP_PORT}"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
